{"name": "test_div[div-zero]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 100\n  +None\n  -100", "trace": "self = <test_pytest.homework.test_calc_new.TestCalc object at 0x00000266960AFB00>\nget_calc = <test_pytest.homework.calculator.Calculator object at 0x00000266960209E8>, get_div_datas = [100, 0, 100]\n\n    @pytest.mark.run(order=4)\n    def test_div(self, get_calc, get_div_datas):\n        result = None\n        try:\n            result = get_calc.div(get_div_datas[0], get_div_datas[1])\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_div_datas[2]\nE       assert None == 100\nE         +None\nE         -100\n\ntest_calc_new.py:38: AssertionError"}, "parameters": [{"name": "get_div_datas", "value": "[100, 0, 100]"}], "start": 1610804889531, "stop": 1610804889531, "uuid": "af218639-9d49-42e6-9cc2-4ee3af2b864d", "historyId": "6676c55c72d5aaccdfa699406fc633b3", "testCaseId": "0aea4d4aff9a90e92a13c7afbc9a7fb3", "fullName": "homework.test_calc_new.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "parentSuite", "value": "homework"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-B1515VS"}, {"name": "thread", "value": "4300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "homework.test_calc_new"}]}