{"name": "test_div[div-other]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'rr'\n  +None\n  -'rr'", "trace": "self = <test_pytest.homework.test_calc_new.TestCalc object at 0x00000266960CF5F8>\nget_calc = <test_pytest.homework.calculator.Calculator object at 0x00000266960209E8>, get_div_datas = ['rr', 'rr', 'rr']\n\n    @pytest.mark.run(order=4)\n    def test_div(self, get_calc, get_div_datas):\n        result = None\n        try:\n            result = get_calc.div(get_div_datas[0], get_div_datas[1])\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_div_datas[2]\nE       AssertionError: assert None == 'rr'\nE         +None\nE         -'rr'\n\ntest_calc_new.py:38: AssertionError"}, "parameters": [{"name": "get_div_datas", "value": "['rr', 'rr', 'rr']"}], "start": 1610804889523, "stop": 1610804889523, "uuid": "4241be5e-c96b-4b2a-b774-8bf492a0f3e6", "historyId": "e9074670f0430af8952756eeddf0b7d0", "testCaseId": "0aea4d4aff9a90e92a13c7afbc9a7fb3", "fullName": "homework.test_calc_new.TestCalc#test_div", "labels": [{"name": "tag", "value": "run(order=4)"}, {"name": "parentSuite", "value": "homework"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-B1515VS"}, {"name": "thread", "value": "4300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "homework.test_calc_new"}]}